### ISSUE TITLE
All registered URLs

### ISSUE THREAD

**Issue by MineJoke** [danieldaeschle/swapy#3]
## Submitting...
- [ ] Bug
- [x] Feature
- [ ] Question
- [ ] Documentation issue

## Feature:

A method to get all registered URLs.
I already implemented something based on the Source Code I've read.

```python
def all_urls():
    return list(map(str, state('__main__').url_map.iter_rules()))
```

**Comment by danieldaeschle** [comment]
Just use `state(__name__).routes.keys()` ??

**Comment by MineJoke** [comment]
Make it easier accesible?

**Comment by danieldaeschle** [comment]
All routes isn't something which is important often. Why it should be accessable with `routes() (.keys())` instead of `state(__name__).routes (.keys())`?
