### ISSUE TITLE
Documentation for the Request class

### ISSUE THREAD

**Issue by MineJoke** [danieldaeschle/swapy#4]
## Submitting...
- [ ] Bug
- [x] Feature
- [ ] Question
- [X] Documentation issue

## Documentation Feature

If you want to get the GET arguments on a URL, for example url:port/?foo=bar, there is no documentation on how to do this. At the moment the only way to find out how it works is by following the request back to its roots. At the end you land at the BaseRequest object from the werkzeug framework(?). There you find out, that the function (a cached_property function thing) is called args.
Please consider adding just a little documentation for cases like this.

**Comment by danieldaeschle** [comment]
Created a section in "Dive deeper". Content will coming soon.
https://github.com/danieldaeschle/swapy/wiki/Dive-Deeper#request-object

**Comment by danieldaeschle** [comment]
Docs finished. Please check if it is okay.
